### ISSUE TITLE
Add Ethereum provider for Ethereum service

### ISSUE THREAD

**Issue by twhay** [DIN-center/din-caddy-plugins#3]
Add Covalent as an Ethereum provider (endpoint will be shared securely). The methods for the Covalent service are the following:

getBlockByHash
getBlockByNumber
getBlockTransactionCountByHash
getBlockTransactionCountByNumber
getLogs
getTransactionByBlockHashAndIndex
getTransactionByBlockNumberAndIndex
getTransactionByHash
getTransactionReceipt
getUncleByBlockHashAndIndex
getUncleByBlockNumberAndIndex
getUncleCountByBlockHash
getUncleCountByBlockNumber

The endpoint is limited to block 18836471 and lower (historical blocks)

**Comment by AusIV** [comment]
As of now we don't have the ability to include a service provider for only some methods, or limit based on static block numbers.

These are doable with some adjustments to the plugins, but we'll need to discuss some requirements.

**Comment by twhay** [comment]
Understood. We have some logic from the Infura proxy we could utilize, but my initial thinking is to have the following requirements:

1. We use the list of methods that a provider gives us to define the methods that this provider will be able to accept
2. We define methods that require state data or non-state data. I can come up with an initial definition of this list.
3. Calls that require state data is sent to services that require a node. Non-state data can be sent to indexers or other providers who have such services.
4. Volumes are split very basically - with two providers, it would only be based on the calls that each provider can serve, and in this case, it would be a simple state calls vs non-state calls split.

**Comment by twhay** [comment]
Putting a note here that there will need to be an Ethereum head tracker service for in order to know the current head block is in order to actually be able to do routing based on block depth.
